# Generated by Django 2.2.1 on 2020-01-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('', 'Select Gender'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=8),
        ),
    ]
